//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int PassportSeries { get; set; }
        public int PassportNumber { get; set; }
        public int Telephone { get; set; }
        public string Email { get; set; }
        public int InsurancePolicyNumber { get; set; }
        public int TypeOfInsurancePolicy { get; set; }
        public int NameOfTheInsuranceCompany { get; set; }
        public string Post { get; set; }
        public string Gendercod { get; set; }
    
        public virtual NOT NOT { get; set; }
        public virtual TOP TOP { get; set; }
    }
}
